
#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = hu
    sensitivity = 0.2
    accel_profile = flat

    touchpad {
        natural_scroll = true
        scroll_factor = 0.1
    }
}

gesture = 3, horizontal, workspace
