source = ./all/monitors.conf
source = ./all/programs.conf
source = ./all/autostart.conf
source = ./all/env.conf
source = ./all/permission.conf
source = ./all/appearance.conf
source = ./all/input.conf
source = ./all/keybinds.conf
source = ./all/window.conf
