# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

foreground              #D8D8D2
background              #0E0E0F
selection_foreground    #0E0E0F
selection_background    #D8D8D2

# black
color0                  #0E0E0F
color8                  #3C3C40

# red
color1                  #C45858
color9                  #D97272

# green
color2                  #4DAF68
color10                 #63C47E

# yellow
color3                  #B8A448
color11                 #CEBB60

# blue
color4                  #4D7DC4
color12                 #6494D9

# magenta
color5                  #9A52C4
color13                 #B068D9

# cyan
color6                  #3EA0A6
color14                 #55B8BC

# white
color7                  #BEBEBA
color15                 #D8D8D2
