# https://sw.kovidgoyal.net/kitty/conf/#color-scheme

foreground #D9D9D9
background #050505
selection_foreground #0D0D0D
selection_background #D9D9D9

# black
color0 #0D0D0D
color8 #262626

# red
color1 #FF4D4D
color9 #FF8080

# green
color2  #4DB24D
color10 #94D194

# yellow
color3  #D2D22D
color11 #D7D775

# blue
color4  #3C71DD
color12 #6495ED

# magenta
color5  #D65CD6
color13 #E87DE8

# cyan
color6  #66C3CC
color14 #8CD2D9

#white
color7  #F2F2F2
color15 #D9D9D9
