include ./all/fonts.conf
include ./all/cursor.conf
include ./all/scrollback.conf
include ./all/mouse.conf
include ./all/performance.conf
include ./all/bell.conf
include ./all/window.conf
include ./all/tab.conf
include ./all/color.conf
