# https://sw.kovidgoyal.net/kitty/conf/#scrollback

scrollbar always
scrollbar_jump_on_click no
scrollbar_handle_opacity 1.0
scrollbar_radius 0.5
scrollbar_gap 0
wheel_scroll_multiplier 2.5
touch_scroll_multiplier 2.5
