# https://sw.kovidgoyal.net/kitty/conf/#keyboard-shortcuts

map ctrl+shift+3 change_font_size all +2.0
map ctrl+shift+1 change_font_size all -2.0
map ctrl+shift+2 change_font_size all 0
map ctrl+shift+o open_url_with_hints
