# https://sw.kovidgoyal.net/kitty/conf/#tab-bar

tab_bar_edge top
tab_bar_style fade
tab_fade 1 1 1
tab_title_max_length 10
active_tab_foreground   #B3E5B3
active_tab_background   #262626
active_tab_font_style   normal
inactive_tab_foreground #262626
inactive_tab_background #B3E5B3
inactive_tab_font_style normal
