include ./configs/fonts.conf
include ./configs/cursor.conf
include ./configs/scrollback.conf
include ./configs/mouse.conf
include ./configs/performance.conf
include ./configs/bell.conf
include ./configs/window.conf
include ./configs/tab.conf
include ./configs/color.conf
include ./configs/shortcuts.conf
