# https://sw.kovidgoyal.net/kitty/conf/#scrollback

scrollbar always
scrollbar_jump_on_click no
scrollbar_width 0.85
scrollbar_hover_width 0.85
scrollbar_handle_opacity 0.5
scrollbar_radius 0.5
scrollbar_track_hover_opacity 0.05
wheel_scroll_multiplier 2.5
touch_scroll_multiplier 2.5
